remove literal type on url type
DanielaGC/UsagiAPI pull request #5
Opened 2021-05-25 19:53 UTC by Tsugami

the literal string type has limitations, in comparison for example. but the url cannot be of the literal type because it can be changed in the future.

2021-05-26 17:01 UTC, nayvcake requested changes
Before accepting this pr .. This needs to be implemented.

2021-05-26 17:02 UTC, NavyCake requested changes
```js
async _request() : Promise<string>;
```

2021-05-26 19:06 UTC, Tsugami commented
> ```js
> async _request() : Promise<string>;
> ```
the pr is not related to this, but I will add

2021-05-27 15:46 UTC, NavyCake approved these changes
Perfect! Thanks for the PR. 😊

2021-06-02 03:30 UTC, merged